[package]
name = "methods-guest"
version = "0.1.0"
edition = "2021"

[workspace]

[dependencies]
risc0-zkvm = { version = "0.14.0", default-features = false, features = [
    "std",
] }
matcher-core = { path = "../../core" }
